server.port: 8282

debug: false

logging:
  level:
    com.note.noteoverflow: debug
    org.springframework.servlet: debug
    org.hibernate.type.descriptor.spl.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note
    username: eoghks
    password: qwer1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
